apiVersion: v1
kind: Pod
metadata:
  name: my-second-pod
  labels:
    name: my-second-pod
spec:
  containers:
  - name: my-second-pod-nginx
    image: nginx

    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  - name: my-second-pod-centos
    image: centos
    command: ["/bin/sh","-c","while : ; do curl http://localhost:80/; sleep 10; done"]
    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"