apiVersion: v1
kind: Pod
metadata:
  name: myapp-local-pvc
 
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['/bin/bash','-ec','cat /data/application/data.txt']
    
    volumeMounts:
    - mountPath: /data/application
      name: local-volume
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"   
    
   
      
  volumes:
  - name: local-volume
    persistentVolumeClaim:
      claimName: pvc-local     
    
